# Generated by Django 5.1.6 on 2025-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo1', models.ImageField(upload_to='photos/')),
                ('photo2', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
